    
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
  jpa:
    show-sql: true
server:
  port: 8081
env:
  test3
girl:
  name: lili
  age: 19
