    
spring:
  application:
    name: order
  rabbitmq:
    host: 192.168.56.101
    port: 5672
    username: guest
    password: guest    
  jpa:
    show-sql: true
env:
  test3
girl:
  name: lili
  age: 19
